"use client"

import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type LanguageContextType = {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState('en');

  useEffect(() => {
    const storedLang = localStorage.getItem('skillclick_lang');
    if (storedLang) {
        setLanguageState(storedLang);
    }
  }, []);

  const setLanguage = (lang: string) => {
      setLanguageState(lang);
      localStorage.setItem('skillclick_lang', lang);
  };

  const translations: Record<string, Record<string, string>> = {
    // === 🇺🇸 ENGLESKI ===
    en: {
      back: "Back",
      backHome: "Back to Home",
      
      // PI LOGIN
      piLoginBtn: "Login with Pi",
      piLoginDesc: "Access your account securely using Pi Network.",
      piLoginDisclaimer: "By clicking, you allow SkillClick to verify your Pi account.",
      piConnecting: "Connecting to Pi Network...",
      piVerifying: "Verifying...",
      piBrowserError: "Please open this app in the Pi Browser.",
      piAuthFailed: "Authentication failed. Try again.",
      piWelcomeUser: "Welcome",

      welcomeBack: "Welcome Back",
      securedBy: "Secured by Invictus System",
      loading: "Loading...",
      
      // Navigacija
      navLogin: "Login",
      navJoin: "Join",
      navPostService: "Post a Service",
      navProfile: "My Profile",
      navAdminPanel: "Admin Panel",
      navLogout: "Log Out",
      
      // Hero & Kategorije
      heroTitle: "Find skill, pay with Pi",
      heroSubtitle: "Global marketplace for the Pi Network community.",
      catDesign: "Graphics & Design",
      catMarketing: "Digital Marketing",
      catWriting: "Writing & Translation",
      catVideo: "Video & Animation",
      catTech: "Programming & Tech",
      catBusiness: "Business",
      catLifestyle: "Lifestyle",
      
      // Pretraga
      searchPlaceholder: "What service are you looking for?",
      searchBtn: "Search",
      popularTag: "Popular:",
      adsTitle: "Popular Services",
      exploreBest: "Explore the best offers",
      viewAll: "View All",
      noReviews: "No reviews yet.",
      
      // Create Service
      createTitle: "Post a New Service",
      createSubtitle: "Showcase your talent to the world",
      labelTitle: "Service Title",
      placeholderTitle: "e.g. I will design a modern logo for you",
      labelCategory: "Category",
      selectCategory: "Select a Category",
      labelPrice: "Price (Pi)",
      labelDelivery: "Delivery Time (days)",
      labelDesc: "Description",
      placeholderDesc: "Describe your service in detail...",
      uploadImages: "Upload Images", // ✅ NOVO
      btnPublish: "Publish Service",
      successMessage: "Service posted successfully!",
      
      // Admin & Stats
      masterAdmin: "Master Admin",
      totalEarnings: "Total Earnings",
      activeGigs: "Active Gigs",
      totalUsers: "Total Users",
      manageUsers: "Manage Users",
      manageServices: "Manage Services",
      
      // Service Detail & Seller Profile
      servicePrice: "Service Price",
      aboutService: "About This Service",
      delivery: "Delivery",
      revisions: "Revisions",
      hireSeller: "Hire Seller",
      contactSeller: "Contact Seller",
      memberSince: "Member Since",
      aboutSeller: "About Seller",
      sellerGigs: "Active Gigs by this Seller",
      contact: "Contact",

      // Reviews
      reviewsTitle: "Reviews & Ratings",
      leaveReview: "Leave a Review",
      writeReview: "Write about your experience...",
      submitReview: "Post Review",
      days: "days",
      verifiedSeller: "Verified Seller",
      reviewsCountLabel: "reviews",
      
      // Footer / Misc
      securePayment: "Secure Pi Payment",
      satisfaction: "Satisfaction Guaranteed",
      support: "24/7 Support",
      guestUser: "Guest User",
      
      // Chat
      msgPlaceholder: "Type a message...",
      msgOnline: "Online",
      msgYourMessages: "Your Messages",
      msgTopic: "Topic:",
      msgSystemWelcome: "Welcome to SkillClick chat! 👋",
      msgStartConv: "Starting conversation regarding:"
    },

    // === 🇷🇸 SRPSKI ===
    sr: {
      back: "Nazad",
      backHome: "Nazad na početnu",
      
      piLoginBtn: "Prijavi se sa Pi",
      piLoginDesc: "Pristupite nalogu sigurno koristeći Pi Network.",
      piLoginDisclaimer: "Klikom dozvoljavate verifikaciju vašeg Pi naloga.",
      piConnecting: "Povezivanje na Pi mrežu...",
      piVerifying: "Verifikacija...",
      piBrowserError: "Molimo otvorite aplikaciju u Pi Browser-u.",
      piAuthFailed: "Neuspešna prijava. Pokušajte ponovo.",
      piWelcomeUser: "Dobrodošli",

      welcomeBack: "Dobrodošli nazad",
      securedBy: "Osigurano Invictus Sistemom",
      loading: "Učitavanje...",
      navLogin: "Prijavi se",
      navJoin: "Registruj se",
      navPostService: "Objavi Uslugu",
      navProfile: "Moj Profil",
      navAdminPanel: "Admin Panel",
      navLogout: "Odjavi se",
      heroTitle: "Pronađi veštinu, plati Pi-jem",
      heroSubtitle: "Globalna pijaca za Pi Network zajednicu.",
      catDesign: "Grafika i Dizajn",
      catMarketing: "Digitalni Marketing",
      catWriting: "Pisanje i Prevod",
      catVideo: "Video i Animacija",
      catTech: "Programiranje i Tehnika",
      catBusiness: "Biznis",
      catLifestyle: "Životni stil",
      searchPlaceholder: "Koju uslugu tražiš?",
      searchBtn: "Pretraži",
      popularTag: "Popularno:",
      adsTitle: "Popularne Usluge",
      exploreBest: "Istražite najbolje ponude",
      viewAll: "Pogledaj sve",
      noReviews: "Još uvek nema recenzija.",
      createTitle: "Objavi Novu Uslugu",
      createSubtitle: "Pokaži svoj talenat svetu",
      labelTitle: "Naslov Usluge",
      placeholderTitle: "npr. Dizajniraću moderan logo za vas",
      labelCategory: "Kategorija",
      selectCategory: "Izaberi kategoriju",
      labelPrice: "Cena (Pi)",
      labelDelivery: "Vreme isporuke (dana)",
      labelDesc: "Opis",
      placeholderDesc: "Opišite vašu uslugu detaljno...",
      uploadImages: "Postavi Slike", // ✅ NOVO
      btnPublish: "Objavi Uslugu",
      successMessage: "Usluga uspešno objavljena!",
      masterAdmin: "Glavni Admin",
      totalEarnings: "Ukupna Zarada",
      activeGigs: "Aktivni Oglasi",
      totalUsers: "Ukupno Korisnika",
      manageUsers: "Upravljanje Korisnicima",
      manageServices: "Upravljanje Oglasima",
      servicePrice: "Cena Usluge",
      aboutService: "O Ovoj Usluzi",
      delivery: "Isporuka",
      revisions: "Revizije",
      hireSeller: "Angažuj",
      contactSeller: "Kontaktiraj",
      
      memberSince: "Član od",
      aboutSeller: "O Prodavcu",
      sellerGigs: "Aktivni Oglasi",
      contact: "Kontaktiraj",

      reviewsTitle: "Recenzije i Ocene",
      leaveReview: "Ostavite utisak",
      writeReview: "Napišite vaše iskustvo...",
      submitReview: "Postavi Recenziju",
      days: "dana",
      verifiedSeller: "Verifikovan prodavac",
      reviewsCountLabel: "recenzija",
      securePayment: "Sigurno Pi plaćanje",
      satisfaction: "Zadovoljstvo garantovano",
      support: "24/7 Podrška",
      guestUser: "Gost",
      msgPlaceholder: "Napiši poruku...",
      msgOnline: "Na mreži",
      msgYourMessages: "Vaše poruke",
      msgTopic: "Tema:",
      msgSystemWelcome: "Dobrodošli u SkillClick ćaskanje! 👋",
      msgStartConv: "Započinjete razgovor u vezi:"
    },

    // === 🇮🇳 HINDI ===
    hi: {
      back: "Wapas",
      backHome: "Home par wapas",
      piLoginBtn: "Pi se Login Karen",
      piLoginDesc: "Pi Network ka upyog karke apne account tak surakshit pahunchein.",
      piLoginDisclaimer: "Click karke, aap SkillClick ko apne Pi account ko verify karne ki anumati dete hain.",
      piConnecting: "Pi Network se connect ho raha hai...",
      piVerifying: "Janch ho rahi hai...",
      piBrowserError: "Kripya is app ko Pi Browser mein kholein.",
      piAuthFailed: "Login vifal raha. Phir se koshish karen.",
      piWelcomeUser: "Swagat hai",

      welcomeBack: "Wapas Swagat Hai",
      securedBy: "Invictus dwara surakshit",
      loading: "Load ho raha hai...",
      navLogin: "Login",
      navJoin: "Shamil Hon",
      navPostService: "Seva Post Karen",
      navProfile: "Mera Profile",
      navAdminPanel: "Admin Panel",
      navLogout: "Log Out",
      heroTitle: "Kaushal khojen, Pi se bhugtan karen",
      catDesign: "Graphics aur Design",
      catMarketing: "Digital Marketing",
      catWriting: "Lekhan aur Anuvaad",
      catVideo: "Video aur Animation",
      catTech: "Programming aur Tech",
      catBusiness: "Vyapar",
      catLifestyle: "Jivan Shaili",
      searchPlaceholder: "Aap kis seva ki talash kar rahe hain?",
      searchBtn: "Khojein",
      popularTag: "Lokpriya:",
      adsTitle: "Lokpriya Sevayein",
      exploreBest: "Behtarin prastav dekhein",
      viewAll: "Sabhi Dekhein",
      noReviews: "Abhi tak koi samiksha nahi.",
      createTitle: "Nayi Seva Post Karen",
      createSubtitle: "Apna hunar duniya ko dikhayein",
      labelTitle: "Seva ka Shirshak",
      placeholderTitle: "Jaise: Main ek logo design karunga",
      labelCategory: "Varg (Category)",
      selectCategory: "Varg chunein",
      labelPrice: "Mulya (Pi)",
      labelDelivery: "Delivery Time (din)",
      labelDesc: "Vivaran",
      placeholderDesc: "Apni seva ke bare mein batayein...",
      uploadImages: "Tasveeren Upload Karen", // ✅ NOVO
      btnPublish: "Seva Prakashit Karen",
      successMessage: "Seva safaltapurvak post ki gayi!",
      masterAdmin: "Master Admin",
      totalEarnings: "Kul Kamai",
      activeGigs: "Active Gigs",
      totalUsers: "Kul Users",
      manageUsers: "Users Prabandhan",
      manageServices: "Services Prabandhan",
      servicePrice: "Seva Mulya",
      aboutService: "Is Seva Ke Bare Mein",
      delivery: "Delivery",
      revisions: "Sanshodhan",
      hireSeller: "Seller Hire Karen",
      contactSeller: "Sampark Karen",

      memberSince: "Sadasya se",
      aboutSeller: "Vikreta ke bare mein",
      sellerGigs: "Is vikreta ki sevaen",
      contact: "Sampark karen",

      reviewsTitle: "Samiksha aur Rating",
      leaveReview: "Samiksha Chhodein",
      writeReview: "Apna anubhav ke bare mein likhein...",
      submitReview: "Post Karen",
      days: "din",
      verifiedSeller: "Satyapit Seller",
      reviewsCountLabel: "samikshayen",
      securePayment: "Surakshit Pi Bhugtan",
      satisfaction: "Santushti Ki Guarantee",
      support: "24/7 Sahayata",
      guestUser: "Mehman",
      msgPlaceholder: "Sandesh likhein...",
      msgOnline: "Online",
      msgYourMessages: "Aapke Sandesh",
      msgTopic: "Vishay:",
      msgSystemWelcome: "SkillClick chat mein swagat hai!",
      msgStartConv: "Baatcheet shuru:"
    },

    // === 🇨🇳 KINESKI ===
    zh: {
      back: "返回",
      backHome: "返回首页",
      piLoginBtn: "使用 Pi 登录",
      piLoginDesc: "使用 Pi Network 安全访问您的帐户。",
      piLoginDisclaimer: "点击即表示您允许 SkillClick 验证您的 Pi 帐户。",
      piConnecting: "正在连接 Pi Network...",
      piVerifying: "正在验证...",
      piBrowserError: "请在 Pi 浏览器中打开此应用。",
      piAuthFailed: "验证失败。请重试。",
      piWelcomeUser: "欢迎",

      welcomeBack: "欢迎回来",
      securedBy: "由 Invictus 系统保护",
      loading: "加载中...",
      navLogin: "登录",
      navJoin: "加入",
      navPostService: "发布服务",
      navProfile: "我的主页",
      navAdminPanel: "管理面板",
      navLogout: "退出",
      heroTitle: "寻找技能，用 Pi 支付",
      catDesign: "图形与设计",
      catMarketing: "数字营销",
      catWriting: "写作与翻译",
      catVideo: "视频与动画",
      catTech: "编程与技术",
      catBusiness: "商业",
      catLifestyle: "生活方式",
      searchPlaceholder: "您在寻找什么服务？",
      searchBtn: "搜索",
      popularTag: "热门:",
      adsTitle: "热门服务",
      exploreBest: "探索最佳优惠",
      viewAll: "查看全部",
      noReviews: "暂无评论。",
      createTitle: "发布新服务",
      createSubtitle: "向世界展示您的才华",
      labelTitle: "服务标题",
      placeholderTitle: "例如：我将为您设计一个现代标志",
      labelCategory: "类别",
      selectCategory: "选择类别",
      labelPrice: "价格 (Pi)",
      labelDelivery: "交付时间 (天)",
      labelDesc: "描述",
      placeholderDesc: "详细描述您的服务...",
      uploadImages: "上传图片", // ✅ NOVO
      btnPublish: "发布服务",
      successMessage: "服务发布成功！",
      masterAdmin: "超级管理员",
      totalEarnings: "总收入",
      activeGigs: "活跃服务",
      totalUsers: "总用户",
      manageUsers: "管理用户",
      manageServices: "管理服务",
      servicePrice: "服务价格",
      aboutService: "关于此服务",
      delivery: "交付",
      revisions: "修改",
      hireSeller: "雇佣卖家",
      contactSeller: "联系卖家",

      memberSince: "加入时间",
      aboutSeller: "关于卖家",
      sellerGigs: "卖家的活跃服务",
      contact: "联系",

      reviewsTitle: "评论与评分",
      leaveReview: "留下评论",
      writeReview: "写下您的体验...",
      submitReview: "发布评论",
      days: "天",
      verifiedSeller: "认证卖家",
      reviewsCountLabel: "条评论",
      securePayment: "安全 Pi 支付",
      satisfaction: "满意保证",
      support: "24/7 支持",
      guestUser: "访客",
      msgPlaceholder: "输入消息...",
      msgOnline: "在线",
      msgYourMessages: "您的消息",
      msgTopic: "主题:",
      msgSystemWelcome: "欢迎来到 SkillClick 聊天!",
      msgStartConv: "开始对话:"
    },

    // === 🇹🇼 TAJVANSKI ===
    tw: {
      back: "返回",
      backHome: "返回首頁",
      piLoginBtn: "使用 Pi 登錄",
      piLoginDesc: "使用 Pi Network 安全訪問您的帳戶。",
      piLoginDisclaimer: "點擊即表示您允許 SkillClick 驗證您的 Pi 帳戶。",
      piConnecting: "正在連接 Pi Network...",
      piVerifying: "正在驗證...",
      piBrowserError: "請在 Pi 瀏覽器中打開此應用。",
      piAuthFailed: "驗證失敗。請重試。",
      piWelcomeUser: "歡迎",

      welcomeBack: "歡迎回來",
      securedBy: "由 Invictus 系統保護",
      loading: "加載中...",
      navLogin: "登錄",
      navJoin: "加入",
      navPostService: "發布服務",
      navProfile: "我的主頁",
      navAdminPanel: "管理面板",
      navLogout: "退出",
      heroTitle: "尋找技能，用 Pi 支付",
      catDesign: "圖形與設計",
      catMarketing: "數字營銷",
      catWriting: "寫作與翻譯",
      catVideo: "視頻與動畫",
      catTech: "編程與技術",
      catBusiness: "商業",
      catLifestyle: "生活方式",
      searchPlaceholder: "您在尋找什麼服務？",
      searchBtn: "搜索",
      popularTag: "熱門:",
      adsTitle: "熱門服務",
      exploreBest: "探索最佳優惠",
      viewAll: "查看全部",
      noReviews: "暫無評論。",
      createTitle: "發布新服務",
      createSubtitle: "向世界展示您的才華",
      labelTitle: "服務標題",
      placeholderTitle: "例如：我將為您設計一個現代標誌",
      labelCategory: "類別",
      selectCategory: "選擇類別",
      labelPrice: "價格 (Pi)",
      labelDelivery: "交付時間 (天)",
      labelDesc: "描述",
      placeholderDesc: "詳細描述您的服務...",
      uploadImages: "上傳圖片", // ✅ NOVO
      btnPublish: "發布服務",
      successMessage: "服務發布成功！",
      masterAdmin: "超級管理員",
      totalEarnings: "總收入",
      activeGigs: "活躍服務",
      totalUsers: "總用戶",
      manageUsers: "管理用戶",
      manageServices: "管理服務",
      servicePrice: "服務價格",
      aboutService: "關於此服務",
      delivery: "交付",
      revisions: "修改",
      hireSeller: "僱傭賣家",
      contactSeller: "聯繫賣家",

      memberSince: "加入時間",
      aboutSeller: "關於賣家",
      sellerGigs: "賣家的活躍服務",
      contact: "聯繫",

      reviewsTitle: "評論與評分",
      leaveReview: "留下評論",
      writeReview: "寫下您的體驗...",
      submitReview: "發布評論",
      days: "天",
      verifiedSeller: "認證賣家",
      reviewsCountLabel: "條評論",
      securePayment: "安全 Pi 支付",
      satisfaction: "滿意保證",
      support: "24/7 支持",
      guestUser: "訪客",
      msgPlaceholder: "輸入消息...",
      msgOnline: "在線",
      msgYourMessages: "您的消息",
      msgTopic: "主題:",
      msgSystemWelcome: "歡迎來到 SkillClick 聊天!",
      msgStartConv: "開始對話:"
    },

    // === 🇮🇩 INDONEŽANSKI ===
    id: {
      back: "Kembali",
      backHome: "Kembali ke Beranda",
      piLoginBtn: "Masuk dengan Pi",
      piLoginDesc: "Akses akun Anda dengan aman menggunakan Jaringan Pi.",
      piLoginDisclaimer: "Dengan mengklik, Anda mengizinkan SkillClick memverifikasi akun Pi Anda.",
      piConnecting: "Menghubungkan ke Jaringan Pi...",
      piVerifying: "Memverifikasi...",
      piBrowserError: "Silakan buka aplikasi ini di Pi Browser.",
      piAuthFailed: "Otentikasi gagal. Coba lagi.",
      piWelcomeUser: "Selamat Datang",

      welcomeBack: "Selamat Datang Kembali",
      securedBy: "Diamankan oleh Invictus",
      loading: "Memuat...",
      navLogin: "Masuk",
      navJoin: "Gabung",
      navPostService: "Pasang Layanan",
      navProfile: "Profil Saya",
      navAdminPanel: "Panel Admin",
      navLogout: "Keluar",
      heroTitle: "Temukan keahlian, bayar dengan Pi",
      catDesign: "Grafis & Desain",
      catMarketing: "Pemasaran Digital",
      catWriting: "Penulisan & Terjemahan",
      catVideo: "Video & Animasi",
      catTech: "Pemrograman & Teknologi",
      catBusiness: "Bisnis",
      catLifestyle: "Gaya Hidup",
      searchPlaceholder: "Layanan apa yang Anda cari?",
      searchBtn: "Cari",
      popularTag: "Populer:",
      adsTitle: "Layanan Populer",
      exploreBest: "Jelajahi penawaran terbaik",
      viewAll: "Lihat Semua",
      noReviews: "Belum ada ulasan.",
      createTitle: "Pasang Layanan Baru",
      createSubtitle: "Tunjukkan bakat Anda kepada dunia",
      labelTitle: "Judul Layanan",
      placeholderTitle: "misalnya Saya akan mendesain logo modern",
      labelCategory: "Kategori",
      selectCategory: "Pilih Kategori",
      labelPrice: "Harga (Pi)",
      labelDelivery: "Waktu Pengiriman (hari)",
      labelDesc: "Deskripsi",
      placeholderDesc: "Jelaskan layanan Anda secara rinci...",
      uploadImages: "Unggah Gambar", // ✅ NOVO
      btnPublish: "Terbitkan Layanan",
      successMessage: "Layanan berhasil diposting!",
      masterAdmin: "Master Admin",
      totalEarnings: "Total Pendapatan",
      activeGigs: "Gigs Aktif",
      totalUsers: "Total Pengguna",
      manageUsers: "Kelola Pengguna",
      manageServices: "Kelola Layanan",
      servicePrice: "Harga Layanan",
      aboutService: "Tentang Layanan Ini",
      delivery: "Pengiriman",
      revisions: "Revisi",
      hireSeller: "Sewa Penjual",
      contactSeller: "Hubungi Penjual",
      
      memberSince: "Anggota Sejak",
      aboutSeller: "Tentang Penjual",
      sellerGigs: "Layanan Aktif",
      contact: "Hubungi",

      reviewsTitle: "Ulasan & Peringkat",
      leaveReview: "Berikan Ulasan",
      writeReview: "Tulis pengalaman Anda...",
      submitReview: "Kirim Ulasan",
      days: "hari",
      verifiedSeller: "Penjual Terverifikasi",
      reviewsCountLabel: "ulasan",
      securePayment: "Pembayaran Pi Aman",
      satisfaction: "Kepuasan Dijamin",
      support: "Dukungan 24/7",
      guestUser: "Tamu",
      msgPlaceholder: "Ketik pesan...",
      msgOnline: "Online",
      msgYourMessages: "Pesan Anda",
      msgTopic: "Topik:",
      msgSystemWelcome: "Selamat datang di obrolan!",
      msgStartConv: "Memulai obrolan:"
    }
  };

  const t = (key: string) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    return { language: 'en', setLanguage: () => {}, t: (key: string) => key };
  }
  return context;
};
