"use client"

import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type LanguageContextType = {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState('en');

  useEffect(() => {
    // Provera da li smo u browser-u pre pristupa localStorage
    if (typeof window !== 'undefined') {
        const storedLang = localStorage.getItem('skillclick_lang');
        if (storedLang) {
            setLanguageState(storedLang);
        }
    }
  }, []);

  const setLanguage = (lang: string) => {
      setLanguageState(lang);
      if (typeof window !== 'undefined') {
          localStorage.setItem('skillclick_lang', lang);
      }
  };

  const translations: Record<string, Record<string, string>> = {
    // === 🇺🇸 ENGLESKI ===
    en: {
      back: "Back",
      backHome: "Back to Home",
      piLoginBtn: "Login with Pi",
      piLoginDesc: "Access your account securely using Pi Network.",
      piLoginDisclaimer: "By clicking, you allow SkillClick to verify your Pi account.",
      piConnecting: "Connecting to Pi Network...",
      piVerifying: "Verifying...",
      piBrowserError: "Please open this app in the Pi Browser.",
      piAuthFailed: "Authentication failed. Try again.",
      piWelcomeUser: "Welcome",
      welcomeBack: "Welcome Back",
      securedBy: "Secured by Invictus System",
      loading: "Loading...",
      navLogin: "Login",
      navJoin: "Join",
      navPostService: "Post a Service",
      navProfile: "My Profile",
      navAdminPanel: "Admin Panel",
      navLogout: "Log Out",
      heroTitle: "Find skill, pay with Pi",
      heroSubtitle: "Global marketplace for the Pi Network community.",
      catDesign: "Graphics & Design",
      catMarketing: "Digital Marketing",
      catWriting: "Writing & Translation",
      catVideo: "Video & Animation",
      catTech: "Programming & Tech",
      catBusiness: "Business",
      catLifestyle: "Lifestyle",
      searchPlaceholder: "What service are you looking for?",
      searchBtn: "Search",
      popularTag: "Popular:",
      adsTitle: "Popular Services",
      exploreBest: "Explore the best offers",
      viewAll: "View All",
      noReviews: "No reviews yet.",
      createTitle: "Post a New Service",
      createSubtitle: "Showcase your talent to the world",
      labelTitle: "Service Title",
      placeholderTitle: "e.g. I will design a modern logo for you",
      labelCategory: "Category",
      selectCategory: "Select a Category",
      labelPrice: "Price (Pi)",
      labelDelivery: "Delivery Time (days)",
      labelDesc: "Description",
      placeholderDesc: "Describe your service in detail...",
      uploadImages: "Upload Images",
      uploadHint: "Max 2MB per image",
      coverImage: "Cover Image",
      imageLabel: "Image",
      btnPublish: "Publish Service",
      successMessage: "Service posted successfully!",
      masterAdmin: "Master Admin",
      totalEarnings: "Total Earnings",
      activeGigs: "Active Gigs",
      totalUsers: "Total Users",
      manageUsers: "Manage Users",
      manageServices: "Manage Services",
      servicePrice: "Service Price",
      aboutService: "About This Service",
      delivery: "Delivery",
      revisions: "Revisions",
      hireSeller: "Hire Seller",
      contactSeller: "Contact Seller",
      memberSince: "Member Since",
      aboutSeller: "About Seller",
      sellerGigs: "Active Gigs by this Seller",
      contact: "Contact",
      reviewsTitle: "Reviews & Ratings",
      leaveReview: "Leave a Review",
      writeReview: "Write about your experience...",
      submitReview: "Post Review",
      days: "days",
      verifiedSeller: "Verified Seller",
      reviewsCountLabel: "reviews",
      securePayment: "Secure Pi Payment",
      satisfaction: "Satisfaction Guaranteed",
      support: "24/7 Support",
      guestUser: "Guest User",
      msgPlaceholder: "Type a message...",
      msgOnline: "Online",
      msgYourMessages: "Your Messages",
      msgTopic: "Topic:",
      msgSystemWelcome: "Welcome to SkillClick chat! 👋",
      msgStartConv: "Starting conversation regarding:",
      notificationsTitle: "Notifications",
      new: "new",
      noNotifications: "No new notifications",
      earnings: "Earnings",
      member: "Member of SkillClick",
      tabOrders: "My Purchases",
      tabSales: "My Sales",
      tabWallet: "Wallet & Info",
      tabFavorites: "Favorites",
      noPurchases: "No purchases yet.",
      noSales: "No sales yet.",
      noFavorites: "No favorite ads yet.",
      seller: "Seller",
      buyer: "Buyer",
      date: "Date",
      statusPaid: "PAID",
      statusPending: "PENDING",
      statusWaiting: "Waiting for buyer",
      walletTitle: "Your Pi Payout Wallet",
      walletDesc: "Enter your Public Key (starts with 'G'). Earnings will be sent here automatically.",
      labelWallet: "Pi Wallet Address (G...)",
      btnSave: "Save Address",
      savedMsg: "✅ Address saved! Earnings will arrive automatically.",
      notLogged: "Not Logged In",
      loginReq: "You must login via Pi Browser to view your profile.",
      error: "Error loading profile data.",
      rated: "Rated",
      // --- NOVO DODATO ---
      btnDispute: "Open Dispute",
      btnCancelDispute: "Cancel Dispute",
      statusDisputed: "DISPUTED",
      statusRefunded: "REFUNDED",
      confirmDispute: "Are you sure you want to open a dispute? Funds will be frozen.",
      disputeOpened: "Dispute successfully opened. Admin notified.",
      confirmCancelDispute: "Are you sure you want to cancel the dispute? Order will return to pending.",
      disputeCanceled: "Dispute successfully canceled.",
      pendingAdWarning: "PREVIEW: This gig is pending approval and is not publicly visible!",
      buyBtn: "Buy Now",
      loginToBuy: "Login to Buy",
      processing: "Processing...",
      buySelfError: "You cannot buy your own service.",
      confirmBuyMsg: "Are you sure you want to buy this service for",
      buySuccess: "Order created successfully!",
      incompletePaymentFixed: "✅ Stuck transaction cleared! Please click buy again."
    },

    // === 🇷🇸 SRPSKI ===
    sr: {
      back: "Nazad",
      backHome: "Nazad na početnu",
      piLoginBtn: "Prijavi se sa Pi",
      piLoginDesc: "Pristupite nalogu sigurno koristeći Pi Network.",
      piLoginDisclaimer: "Klikom dozvoljavate verifikaciju vašeg Pi naloga.",
      piConnecting: "Povezivanje na Pi mrežu...",
      piVerifying: "Verifikacija...",
      piBrowserError: "Molimo otvorite aplikaciju u Pi Browser-u.",
      piAuthFailed: "Neuspešna prijava. Pokušajte ponovo.",
      piWelcomeUser: "Dobrodošli",
      welcomeBack: "Dobrodošli nazad",
      securedBy: "Osigurano Invictus Sistemom",
      loading: "Učitavanje...",
      navLogin: "Prijavi se",
      navJoin: "Registruj se",
      navPostService: "Objavi Uslugu",
      navProfile: "Moj Profil",
      navAdminPanel: "Admin Panel",
      navLogout: "Odjavi se",
      heroTitle: "Pronađi veštinu, plati Pi-jem",
      heroSubtitle: "Globalna pijaca za Pi Network zajednicu.",
      catDesign: "Grafika i Dizajn",
      catMarketing: "Digitalni Marketing",
      catWriting: "Pisanje i Prevod",
      catVideo: "Video i Animacija",
      catTech: "Programiranje i Tehnika",
      catBusiness: "Biznis",
      catLifestyle: "Životni stil",
      searchPlaceholder: "Koju uslugu tražiš?",
      searchBtn: "Pretraži",
      popularTag: "Popularno:",
      adsTitle: "Popularne Usluge",
      exploreBest: "Istražite najbolje ponude",
      viewAll: "Pogledaj sve",
      noReviews: "Još uvek nema recenzija.",
      createTitle: "Objavi Novu Uslugu",
      createSubtitle: "Pokaži svoj talenat svetu",
      labelTitle: "Naslov Usluge",
      placeholderTitle: "npr. Dizajniraću moderan logo za vas",
      labelCategory: "Kategorija",
      selectCategory: "Izaberi kategoriju",
      labelPrice: "Cena (Pi)",
      labelDelivery: "Vreme isporuke (dana)",
      labelDesc: "Opis",
      placeholderDesc: "Opišite vašu uslugu detaljno...",
      uploadImages: "Postavi Slike",
      uploadHint: "Max 2MB po slici",
      coverImage: "Naslovna Slika",
      imageLabel: "Slika",
      btnPublish: "Objavi Uslugu",
      successMessage: "Usluga uspešno objavljena!",
      masterAdmin: "Glavni Admin",
      totalEarnings: "Ukupna Zarada",
      activeGigs: "Aktivni Oglasi",
      totalUsers: "Ukupno Korisnika",
      manageUsers: "Upravljanje Korisnicima",
      manageServices: "Upravljanje Oglasima",
      servicePrice: "Cena Usluge",
      aboutService: "O Ovoj Usluzi",
      delivery: "Isporuka",
      revisions: "Revizije",
      hireSeller: "Angažuj",
      contactSeller: "Kontaktiraj",
      memberSince: "Član od",
      aboutSeller: "O Prodavcu",
      sellerGigs: "Aktivni Oglasi",
      contact: "Kontaktiraj",
      reviewsTitle: "Recenzije i Ocene",
      leaveReview: "Ostavite utisak",
      writeReview: "Napišite vaše iskustvo...",
      submitReview: "Postavi Recenziju",
      days: "dana",
      verifiedSeller: "Verifikovan prodavac",
      reviewsCountLabel: "recenzija",
      securePayment: "Sigurno Pi plaćanje",
      satisfaction: "Zadovoljstvo garantovano",
      support: "24/7 Podrška",
      guestUser: "Gost",
      msgPlaceholder: "Napiši poruku...",
      msgOnline: "Na mreži",
      msgYourMessages: "Vaše poruke",
      msgTopic: "Tema:",
      msgSystemWelcome: "Dobrodošli u SkillClick ćaskanje! 👋",
      msgStartConv: "Započinjete razgovor u vezi:",
      notificationsTitle: "Obaveštenja",
      new: "novih",
      noNotifications: "Nema novih obaveštenja",
      earnings: "Zarada",
      member: "Član platforme SkillClick",
      tabOrders: "Moje Kupovine",
      tabSales: "Moje Prodaje",
      tabWallet: "Novčanik & Info",
      tabFavorites: "Omiljeno",
      noPurchases: "Nemaš kupovina.",
      noSales: "Nemaš prodaja.",
      noFavorites: "Nemaš omiljenih oglasa.",
      seller: "Prodavac",
      buyer: "Kupac",
      date: "Datum",
      statusPaid: "ISPLAĆENO",
      statusPending: "NA ČEKANJU",
      statusWaiting: "Čeka se kupac",
      walletTitle: "Tvoj Pi Novčanik za Isplatu",
      walletDesc: "Ovde unesi svoju Javnu Adresu (Public Key). Tu ti leže zarada automatski.",
      labelWallet: "Pi Wallet Adresa (G...)",
      btnSave: "Sačuvaj Adresu",
      savedMsg: "✅ Adresa sačuvana! Sada ti zarada leže automatski.",
      notLogged: "Nisi ulogovan",
      loginReq: "Moraš se ulogovati kroz Pi Browser da bi video profil.",
      error: "Greška pri učitavanju podataka profila.",
      rated: "Ocenjeno",
      // --- NOVO DODATO ---
      btnDispute: "Pokreni spor",
      btnCancelDispute: "Poništi spor",
      statusDisputed: "U SPORU",
      statusRefunded: "REFUNDIRANO",
      confirmDispute: "Da li ste sigurni da želite da pokrenete spor? Sredstva će biti zamrznuta.",
      disputeOpened: "Spor je uspešno pokrenut. Admin je obavešten.",
      confirmCancelDispute: "Da li ste sigurni da želite da poništite spor? Narudžbina će se vratiti na čekanje.",
      disputeCanceled: "Spor je uspešno poništen.",
      pendingAdWarning: "PREGLED: Ovaj oglas je na čekanju i nije javno vidljiv na početnoj stranici!",
      buyBtn: "Kupi Odmah",
      loginToBuy: "Prijavi se za kupovinu",
      processing: "Obrada...",
      buySelfError: "Ne možete kupiti sopstvenu uslugu.",
      confirmBuyMsg: "Da li sigurno želiš da kupiš ovu uslugu za",
      buySuccess: "Uspešna kupovina!",
      incompletePaymentFixed: "✅ Sistem je obrisao zaglavljenu transakciju! Klikni ponovo na kupovinu."
    },

    // === 🇮🇳 HINDI ===
    hi: {
      back: "Wapas",
      backHome: "Home par wapas",
      piLoginBtn: "Pi se Login Karen",
      piLoginDesc: "Pi Network ka upyog karke apne account tak surakshit pahunchein.",
      piLoginDisclaimer: "Click karke, aap SkillClick ko apne Pi account ko verify karne ki anumati dete hain.",
      piConnecting: "Pi Network se connect ho raha hai...",
      piVerifying: "Janch ho rahi hai...",
      piBrowserError: "Kripya is app ko Pi Browser mein kholein.",
      piAuthFailed: "Login vifal raha. Phir se koshish karen.",
      piWelcomeUser: "Swagat hai",
      welcomeBack: "Wapas Swagat Hai",
      securedBy: "Invictus dwara surakshit",
      loading: "Load ho raha hai...",
      navLogin: "Login",
      navJoin: "Shamil Hon",
      navPostService: "Seva Post Karen",
      navProfile: "Mera Profile",
      navAdminPanel: "Admin Panel",
      navLogout: "Log Out",
      heroTitle: "Kaushal khojen, Pi se bhugtan karen",
      catDesign: "Graphics aur Design",
      catMarketing: "Digital Marketing",
      catWriting: "Lekhan aur Anuvaad",
      catVideo: "Video aur Animation",
      catTech: "Programming aur Tech",
      catBusiness: "Vyapar",
      catLifestyle: "Jivan Shaili",
      searchPlaceholder: "Aap kis seva ki talash kar rahe hain?",
      searchBtn: "Khojein",
      popularTag: "Lokpriya:",
      adsTitle: "Lokpriya Sevayein",
      exploreBest: "Behtarin prastav dekhein",
      viewAll: "Sabhi Dekhein",
      noReviews: "Abhi tak koi samiksha nahi.",
      createTitle: "Nayi Seva Post Karen",
      createSubtitle: "Apna hunar duniya ko dikhayein",
      labelTitle: "Seva ka Shirshak",
      placeholderTitle: "Jaise: Main ek logo design karunga",
      labelCategory: "Varg (Category)",
      selectCategory: "Varg chunein",
      labelPrice: "Mulya (Pi)",
      labelDelivery: "Delivery Time (din)",
      labelDesc: "Vivaran",
      placeholderDesc: "Apni seva ke bare mein batayein...",
      uploadImages: "Tasveeren Upload Karen",
      uploadHint: "Adhiktam 2MB prati tasveer",
      coverImage: "Cover Tasveer",
      imageLabel: "Tasveer",
      btnPublish: "Seva Prakashit Karen",
      successMessage: "Seva safaltapurvak post ki gayi!",
      masterAdmin: "Master Admin",
      totalEarnings: "Kul Kamai",
      activeGigs: "Active Gigs",
      totalUsers: "Kul Users",
      manageUsers: "Users Prabandhan",
      manageServices: "Services Prabandhan",
      servicePrice: "Seva Mulya",
      aboutService: "Is Seva Ke Bare Mein",
      delivery: "Delivery",
      revisions: "Sanshodhan",
      hireSeller: "Seller Hire Karen",
      contactSeller: "Sampark Karen",
      memberSince: "Sadasya se",
      aboutSeller: "Vikreta ke bare mein",
      sellerGigs: "Is vikreta ki sevaen",
      contact: "Sampark karen",
      reviewsTitle: "Samiksha aur Rating",
      leaveReview: "Samiksha Chhodein",
      writeReview: "Apna anubhav ke bare mein likhein...",
      submitReview: "Post Karen",
      days: "din",
      verifiedSeller: "Satyapit Seller",
      reviewsCountLabel: "samikshayen",
      securePayment: "Surakshit Pi Bhugtan",
      satisfaction: "Santushti Ki Guarantee",
      support: "24/7 Sahayata",
      guestUser: "Mehman",
      msgPlaceholder: "Sandesh likhein...",
      msgOnline: "Online",
      msgYourMessages: "Aapke Sandesh",
      msgTopic: "Vishay:",
      msgSystemWelcome: "SkillClick chat mein swagat hai!",
      msgStartConv: "Baatcheet shuru:",
      notificationsTitle: "Suchnayein",
      new: "nayi",
      noNotifications: "Koi nayi suchna nahi",
      earnings: "कमाई",
      member: "SkillClick सदस्य",
      tabOrders: "मेरी खरीदारी",
      tabSales: "मेरी बिक्री",
      tabWallet: "वॉलेट और जानकारी",
      tabFavorites: "पसंदीदा",
      noPurchases: "अभी तक कोई खरीदारी नहीं।",
      noSales: "अभी तक कोई बिक्री नहीं।",
      noFavorites: "कोई पसंदीदा विज्ञापन नहीं।",
      seller: "विक्रेता",
      buyer: "खरीदार",
      date: "तारीख",
      statusPaid: "भुगतान किया गया",
      statusPending: "लंबित",
      statusWaiting: "खरीदार की प्रतीक्षा",
      walletTitle: "आपका Pi पेआउट वॉलेट",
      walletDesc: "अपनी पब्लिक की (G से शुरू) दर्ज करें। कमाई स्वचालित रूप से यहां भेजी जाएगी।",
      labelWallet: "Pi वॉलेट पता (G...)",
      btnSave: "पता सहेजें",
      savedMsg: "✅ पता सहेजा गया! कमाई स्वचालित रूप से आ जाएगी।",
      notLogged: "लॉग इन नहीं है",
      loginReq: "अपनी प्रोफ़ाइल देखने के लिए आपको Pi Browser के माध्यम से लॉग इन करना होगा।",
      error: "प्रोफ़ाइल डेटा लोड करने में त्रुटि।",
      rated: "रेट किया गया",
      // --- NOVO DODATO ---
      btnDispute: "विवाद खोलें",
      btnCancelDispute: "विवाद रद्द करें",
      statusDisputed: "विवादित",
      statusRefunded: "वापस किया गया",
      confirmDispute: "क्या आप वाकई विवाद खोलना चाहते हैं? फंड फ्रीज हो जाएंगे।",
      disputeOpened: "विवाद सफलतापूर्वक खुल गया।",
      confirmCancelDispute: "क्या आप विवाद रद्द करना चाहते हैं?",
      disputeCanceled: "विवाद रद्द कर दिया गया।",
      pendingAdWarning: "प्रीव्यू: यह विज्ञापन लंबित है!",
      buyBtn: "अभी खरीदें",
      loginToBuy: "खरीदने के लिए लॉगिन करें",
      processing: "प्रोसेसिंग...",
      buySelfError: "आप अपनी सेवा नहीं खरीद सकते।",
      confirmBuyMsg: "क्या आप इसे खरीदना चाहते हैं",
      buySuccess: "सफलतापूर्वक खरीदा गया!",
      incompletePaymentFixed: "✅ रुकी हुई लेन-देन साफ हो गई! कृपया फिर से खरीदें।"
    },

    // === 🇨🇳 KINESKI ===
    zh: {
      back: "返回",
      backHome: "返回首页",
      piLoginBtn: "使用 Pi 登录",
      piLoginDesc: "使用 Pi Network 安全访问您的帐户。",
      piLoginDisclaimer: "点击即表示您允许 SkillClick 验证您的 Pi 帐户。",
      piConnecting: "正在连接 Pi Network...",
      piVerifying: "正在验证...",
      piBrowserError: "请在 Pi 浏览器中打开此应用。",
      piAuthFailed: "验证失败。请重试。",
      piWelcomeUser: "欢迎",
      welcomeBack: "欢迎回来",
      securedBy: "由 Invictus 系统保护",
      loading: "加载中...",
      navLogin: "登录",
      navJoin: "加入",
      navPostService: "发布服务",
      navProfile: "我的主页",
      navAdminPanel: "管理面板",
      navLogout: "退出",
      heroTitle: "寻找技能，用 Pi 支付",
      catDesign: "图形与设计",
      catMarketing: "数字营销",
      catWriting: "写作与翻译",
      catVideo: "视频与动画",
      catTech: "编程与技术",
      catBusiness: "商业",
      catLifestyle: "生活方式",
      searchPlaceholder: "您在寻找什么服务？",
      searchBtn: "搜索",
      popularTag: "热门:",
      adsTitle: "热门服务",
      exploreBest: "探索最佳优惠",
      viewAll: "查看全部",
      noReviews: "暂无评论。",
      createTitle: "发布新服务",
      createSubtitle: "向世界展示您的才华",
      labelTitle: "服务标题",
      placeholderTitle: "例如：我将为您设计一个现代标志",
      labelCategory: "类别",
      selectCategory: "选择类别",
      labelPrice: "价格 (Pi)",
      labelDelivery: "交付时间 (天)",
      labelDesc: "描述",
      placeholderDesc: "详细描述您的服务...",
      uploadImages: "上传图片",
      uploadHint: "每张图片最大 2MB",
      coverImage: "封面图片",
      imageLabel: "图片",
      btnPublish: "发布服务",
      successMessage: "服务发布成功！",
      masterAdmin: "超级管理员",
      totalEarnings: "总收入",
      activeGigs: "活跃服务",
      totalUsers: "总用户",
      manageUsers: "管理用户",
      manageServices: "管理服务",
      servicePrice: "服务价格",
      aboutService: "关于此服务",
      delivery: "交付",
      revisions: "修改",
      hireSeller: "雇佣卖家",
      contactSeller: "联系卖家",
      memberSince: "加入时间",
      aboutSeller: "关于卖家",
      sellerGigs: "卖家的活跃服务",
      contact: "联系",
      reviewsTitle: "评论与评分",
      leaveReview: "留下评论",
      writeReview: "写下您的体验...",
      submitReview: "发布评论",
      days: "天",
      verifiedSeller: "认证卖家",
      reviewsCountLabel: "条评论",
      securePayment: "安全 Pi 支付",
      satisfaction: "满意保证",
      support: "24/7 支持",
      guestUser: "访客",
      msgPlaceholder: "输入消息...",
      msgOnline: "在线",
      msgYourMessages: "您的消息",
      msgTopic: "主题:",
      msgSystemWelcome: "欢迎来到 SkillClick 聊天!",
      msgStartConv: "开始对话:",
      notificationsTitle: "通知",
      new: "新",
      noNotifications: "暂无新通知",
      earnings: "收入",
      member: "SkillClick 会员",
      tabOrders: "我的购买",
      tabSales: "我的销售",
      tabWallet: "钱包 & 信息",
      tabFavorites: "收藏",
      noPurchases: "暂无购买记录。",
      noSales: "暂无销售记录。",
      noFavorites: "没有最喜欢的广告。",
      seller: "卖家",
      buyer: "买家",
      date: "日期",
      statusPaid: "已支付",
      statusPending: "待处理",
      statusWaiting: "等待买家",
      walletTitle: "您的 Pi 收款钱包",
      walletDesc: "输入您的公钥（以 'G' 开头）。收入将自动发送到此处。",
      labelWallet: "Pi 钱包地址 (G...)",
      btnSave: "保存地址",
      savedMsg: "✅ 地址已保存！收入将自动到账。",
      notLogged: "未登录",
      loginReq: "您必须通过 Pi 浏览器登录才能查看个人资料。",
      error: "加载个人资料数据时出错。",
      rated: "已评价",
      // --- NOVO DODATO ---
      btnDispute: "发起争议",
      btnCancelDispute: "取消争议",
      statusDisputed: "争议中",
      statusRefunded: "已退款",
      confirmDispute: "您确定要发起争议吗？资金将被冻结。",
      disputeOpened: "争议已成功发起。",
      confirmCancelDispute: "您确定要取消争议吗？订单将返回待处理状态。",
      disputeCanceled: "争议已成功取消。",
      pendingAdWarning: "预览：此广告正在等待审核，尚未公开可见！",
      buyBtn: "立即购买",
      loginToBuy: "登录后购买",
      processing: "处理中...",
      buySelfError: "您不能购买自己的服务。",
      confirmBuyMsg: "您确定要购买此服务吗，价格为",
      buySuccess: "购买成功！",
      incompletePaymentFixed: "✅ 卡住的交易已清除！请再次点击购买。"
    },

    // === 🇹🇼 TAJVANSKI ===
    tw: {
      back: "返回",
      backHome: "返回首頁",
      piLoginBtn: "使用 Pi 登錄",
      piLoginDesc: "使用 Pi Network 安全訪問您的帳戶。",
      piLoginDisclaimer: "點擊即表示您允許 SkillClick 驗證您的 Pi 帳戶。",
      piConnecting: "正在連接 Pi Network...",
      piVerifying: "正在驗證...",
      piBrowserError: "請在 Pi 瀏覽器中打開此應用。",
      piAuthFailed: "驗證失敗。請重試。",
      piWelcomeUser: "歡迎",
      welcomeBack: "歡迎回來",
      securedBy: "由 Invictus 系統保護",
      loading: "加載中...",
      navLogin: "登錄",
      navJoin: "加入",
      navPostService: "發布服務",
      navProfile: "我的主頁",
      navAdminPanel: "管理面板",
      navLogout: "退出",
      heroTitle: "尋找技能，用 Pi 支付",
      catDesign: "圖形與設計",
      catMarketing: "數字營銷",
      catWriting: "寫作與翻譯",
      catVideo: "視頻與動畫",
      catTech: "編程與技術",
      catBusiness: "商業",
      catLifestyle: "生活方式",
      searchPlaceholder: "您在尋找什麼服務？",
      searchBtn: "搜索",
      popularTag: "熱門:",
      adsTitle: "熱門服務",
      exploreBest: "探索最佳優惠",
      viewAll: "查看全部",
      noReviews: "暫無評論。",
      createTitle: "發布新服務",
      createSubtitle: "向世界展示您的才華",
      labelTitle: "服務標題",
      placeholderTitle: "例如：我將為您設計一個現代標誌",
      labelCategory: "類別",
      selectCategory: "選擇類別",
      labelPrice: "價格 (Pi)",
      labelDelivery: "交付時間 (天)",
      labelDesc: "描述",
      placeholderDesc: "詳細描述您的服務...",
      uploadImages: "上傳圖片",
      uploadHint: "每張圖片最大 2MB",
      coverImage: "封面圖片",
      imageLabel: "圖片",
      btnPublish: "發布服務",
      successMessage: "服務發布成功！",
      masterAdmin: "超級管理員",
      totalEarnings: "總收入",
      activeGigs: "活躍服務",
      totalUsers: "總用戶",
      manageUsers: "管理用戶",
      manageServices: "管理服務",
      servicePrice: "服務價格",
      aboutService: "關於此服務",
      delivery: "交付",
      revisions: "修改",
      hireSeller: "僱傭賣家",
      contactSeller: "聯繫賣家",
      memberSince: "加入時間",
      aboutSeller: "關於賣家",
      sellerGigs: "賣家的活躍服務",
      contact: "聯繫",
      reviewsTitle: "評論與評分",
      leaveReview: "留下評論",
      writeReview: "寫下您的體驗...",
      submitReview: "發布評論",
      days: "天",
      verifiedSeller: "認證賣家",
      reviewsCountLabel: "條評論",
      securePayment: "安全 Pi 支付",
      satisfaction: "滿意保證",
      support: "24/7 支持",
      guestUser: "訪客",
      msgPlaceholder: "輸入消息...",
      msgOnline: "在線",
      msgYourMessages: "您的消息",
      msgTopic: "主題:",
      msgSystemWelcome: "歡迎來到 SkillClick 聊天!",
      msgStartConv: "開始對話:",
      notificationsTitle: "通知",
      new: "新",
      noNotifications: "暫無新通知",
      earnings: "收入",
      member: "SkillClick 會員",
      tabOrders: "我的購買",
      tabSales: "我的銷售",
      tabWallet: "錢包 & 資訊",
      tabFavorites: "收藏",
      noPurchases: "暫無購買記錄。",
      noSales: "暫無銷售記錄。",
      noFavorites: "沒有最喜歡的廣告。",
      seller: "賣家",
      buyer: "買家",
      date: "日期",
      statusPaid: "已支付",
      statusPending: "待處理",
      statusWaiting: "等待買家",
      walletTitle: "您的 Pi 收款錢包",
      walletDesc: "輸入您的公鑰（以 'G' 開頭）。收入將自動發送到此處。",
      labelWallet: "Pi 錢包地址 (G...)",
      btnSave: "保存地址",
      savedMsg: "✅ 地址已保存！收入將自動到帳。",
      notLogged: "未登錄",
      loginReq: "您必須通過 Pi 瀏覽器登錄才能查看個人資料。",
      error: "加載個人資料數據時出錯。",
      rated: "已評價",
      // --- NOVO DODATO ---
      btnDispute: "發起爭議",
      btnCancelDispute: "取消爭議",
      statusDisputed: "爭議中",
      statusRefunded: "已退款",
      confirmDispute: "您確定要發起爭議嗎？資金將被凍結。",
      disputeOpened: "爭議已成功發起。",
      confirmCancelDispute: "您確定要取消爭議嗎？訂單將返回待處理狀態。",
      disputeCanceled: "爭議已成功取消。",
      pendingAdWarning: "預覽：此廣告正在等待審核，尚未公開可見！",
      buyBtn: "立即購買",
      loginToBuy: "登錄後購買",
      processing: "處理中...",
      buySelfError: "您不能購買自己的服務。",
      confirmBuyMsg: "您確定要購買此服務嗎，價格為",
      buySuccess: "購買成功！",
      incompletePaymentFixed: "✅ 卡住的交易已清除！請再次點擊購買。"
    },

    // === 🇮🇩 INDONEŽANSKI ===
    id: {
      back: "Kembali",
      backHome: "Kembali ke Beranda",
      piLoginBtn: "Masuk dengan Pi",
      piLoginDesc: "Akses akun Anda dengan aman menggunakan Jaringan Pi.",
      piLoginDisclaimer: "Dengan mengklik, Anda mengizinkan SkillClick memverifikasi akun Pi Anda.",
      piConnecting: "Menghubungkan ke Jaringan Pi...",
      piVerifying: "Memverifikasi...",
      piBrowserError: "Silakan buka aplikasi ini di Pi Browser.",
      piAuthFailed: "Otentikasi gagal. Coba lagi.",
      piWelcomeUser: "Selamat Datang",
      welcomeBack: "Selamat Datang Kembali",
      securedBy: "Diamankan oleh Invictus",
      loading: "Memuat...",
      navLogin: "Masuk",
      navJoin: "Gabung",
      navPostService: "Pasang Layanan",
      navProfile: "Profil Saya",
      navAdminPanel: "Panel Admin",
      navLogout: "Keluar",
      heroTitle: "Temukan keahlian, bayar dengan Pi",
      catDesign: "Grafis & Desain",
      catMarketing: "Pemasaran Digital",
      catWriting: "Penulisan & Terjemahan",
      catVideo: "Video & Animasi",
      catTech: "Pemrograman & Teknologi",
      catBusiness: "Bisnis",
      catLifestyle: "Gaya Hidup",
      searchPlaceholder: "Layanan apa yang Anda cari?",
      searchBtn: "Cari",
      popularTag: "Populer:",
      adsTitle: "Layanan Populer",
      exploreBest: "Jelajahi penawaran terbaik",
      viewAll: "Lihat Semua",
      noReviews: "Belum ada ulasan.",
      createTitle: "Pasang Layanan Baru",
      createSubtitle: "Tunjukkan bakat Anda kepada dunia",
      labelTitle: "Judul Layanan",
      placeholderTitle: "misalnya Saya akan mendesain logo modern",
      labelCategory: "Kategori",
      selectCategory: "Pilih Kategori",
      labelPrice: "Harga (Pi)",
      labelDelivery: "Waktu Pengiriman (hari)",
      labelDesc: "Deskripsi",
      placeholderDesc: "Jelaskan layanan Anda secara rinci...",
      uploadImages: "Unggah Gambar",
      uploadHint: "Maks 2MB per gambar",
      coverImage: "Gambar Sampul",
      imageLabel: "Gambar",
      btnPublish: "Terbitkan Layanan",
      successMessage: "Layanan berhasil diposting!",
      masterAdmin: "Master Admin",
      totalEarnings: "Total Pendapatan",
      activeGigs: "Gigs Aktif",
      totalUsers: "Total Pengguna",
      manageUsers: "Kelola Pengguna",
      manageServices: "Kelola Layanan",
      servicePrice: "Harga Layanan",
      aboutService: "Tentang Layanan Ini",
      delivery: "Pengiriman",
      revisions: "Revisi",
      hireSeller: "Sewa Penjual",
      contactSeller: "Hubungi Penjual",
      memberSince: "Anggota Sejak",
      aboutSeller: "Tentang Penjual",
      sellerGigs: "Layanan Aktif",
      contact: "Hubungi",
      reviewsTitle: "Ulasan & Peringkat",
      leaveReview: "Berikan Ulasan",
      writeReview: "Tulis pengalaman Anda...",
      submitReview: "Kirim Ulasan",
      days: "hari",
      verifiedSeller: "Penjual Terverifikasi",
      reviewsCountLabel: "ulasan",
      securePayment: "Pembayaran Pi Aman",
      satisfaction: "Kepuasan Dijamin",
      support: "Dukungan 24/7",
      guestUser: "Tamu",
      msgPlaceholder: "Ketik pesan...",
      msgOnline: "Online",
      msgYourMessages: "Pesan Anda",
      msgTopic: "Topik:",
      msgSystemWelcome: "Selamat datang di obrolan!",
      msgStartConv: "Memulai obrolan:",
      notificationsTitle: "Notifikasi",
      new: "baru",
      noNotifications: "Tidak ada notifikasi baru",
      earnings: "Pendapatan",
      member: "Anggota SkillClick",
      tabOrders: "Pembelian Saya",
      tabSales: "Penjualan Saya",
      tabWallet: "Dompet & Info",
      tabFavorites: "Favorit",
      noPurchases: "Belum ada pembelian.",
      noSales: "Belum ada penjualan.",
      noFavorites: "Tidak ada iklan favorit.",
      seller: "Penjual",
      buyer: "Pembeli",
      date: "Tanggal",
      statusPaid: "DIBAYAR",
      statusPending: "TERTUNDA",
      statusWaiting: "Menunggu pembeli",
      walletTitle: "Dompet Pencairan Pi Anda",
      walletDesc: "Masukkan Public Key Anda (dimulai dengan 'G'). Pendapatan akan dikirim ke sini secara otomatis.",
      labelWallet: "Alamat Dompet Pi (G...)",
      btnSave: "Simpan Alamat",
      savedMsg: "✅ Alamat disimpan! Pendapatan akan masuk secara otomatis.",
      notLogged: "Belum Masuk",
      loginReq: "Anda harus masuk melalui Pi Browser untuk melihat profil.",
      error: "Kesalahan memuat data profil.",
      rated: "Dinilai",
      // --- NOVO DODATO ---
      btnDispute: "Buka Sengketa",
      btnCancelDispute: "Batal Sengketa",
      statusDisputed: "SENGKETA",
      statusRefunded: "DIKEMBALIKAN",
      confirmDispute: "Yakin ingin membuka sengketa? Dana akan dibekukan.",
      disputeOpened: "Sengketa berhasil dibuka.",
      confirmCancelDispute: "Yakin ingin membatalkan sengketa?",
      disputeCanceled: "Sengketa dibatalkan.",
      pendingAdWarning: "PRATINJAU: Iklan ini menunggu persetujuan!",
      buyBtn: "Beli Sekarang",
      loginToBuy: "Masuk untuk Membeli",
      processing: "Memproses...",
      buySelfError: "Anda tidak dapat membeli layanan Anda sendiri.",
      confirmBuyMsg: "Yakin ingin membeli layanan ini seharga",
      buySuccess: "Pembelian berhasil!",
      incompletePaymentFixed: "✅ Transaksi macet dibersihkan! Silakan klik beli lagi."
    },

    // === 🇰🇷 KOREJSKI ===
    ko: {
      back: "뒤로",
      backHome: "홈으로 돌아가기",
      piLoginBtn: "Pi로 로그인",
      piLoginDesc: "Pi Network를 사용하여 계정에 안전하게 액세스하세요.",
      piLoginDisclaimer: "클릭하면 SkillClick이 Pi 계정을 확인하도록 허용하게 됩니다.",
      piConnecting: "Pi Network에 연결 중...",
      piVerifying: "확인 중...",
      piBrowserError: "Pi 브라우저에서 이 앱을 열어주세요.",
      piAuthFailed: "인증 실패. 다시 시도해주세요.",
      piWelcomeUser: "환영합니다",
      welcomeBack: "다시 오신 것을 환영합니다",
      securedBy: "Invictus 시스템으로 보호됨",
      loading: "로딩 중...",
      navLogin: "로그인",
      navJoin: "가입하기",
      navPostService: "서비스 등록",
      navProfile: "내 프로필",
      navAdminPanel: "관리자 패널",
      navLogout: "로그아웃",
      heroTitle: "기술을 찾고, Pi로 결제하세요",
      heroSubtitle: "Pi Network 커뮤니티를 위한 글로벌 마켓플레이스.",
      catDesign: "그래픽 및 디자인",
      catMarketing: "디지털 마케팅",
      catWriting: "작문 및 번역",
      catVideo: "비디오 및 애니메이션",
      catTech: "프로그래밍 및 기술",
      catBusiness: "비즈니스",
      catLifestyle: "라이프스타일",
      searchPlaceholder: "어떤 서비스를 찾고 계신가요?",
      searchBtn: "검색",
      popularTag: "인기:",
      adsTitle: "인기 서비스",
      exploreBest: "최고의 혜택 탐색하기",
      viewAll: "모두 보기",
      noReviews: "아직 리뷰가 없습니다.",
      createTitle: "새로운 서비스 등록",
      createSubtitle: "당신의 재능을 세상에 보여주세요",
      labelTitle: "서비스 제목",
      placeholderTitle: "예: 현대적인 로고를 디자인해 드립니다",
      labelCategory: "카테고리",
      selectCategory: "카테고리 선택",
      labelPrice: "가격 (Pi)",
      labelDelivery: "배송 기간 (일)",
      labelDesc: "설명",
      placeholderDesc: "서비스를 자세히 설명해주세요...",
      uploadImages: "이미지 업로드",
      uploadHint: "이미지당 최대 2MB",
      coverImage: "커버 이미지",
      imageLabel: "이미지",
      btnPublish: "서비스 게시",
      successMessage: "서비스가 성공적으로 등록되었습니다!",
      masterAdmin: "마스터 관리자",
      totalEarnings: "총 수익",
      activeGigs: "활성 서비스",
      totalUsers: "총 사용자",
      manageUsers: "사용자 관리",
      manageServices: "서비스 관리",
      servicePrice: "서비스 가격",
      aboutService: "이 서비스에 대하여",
      delivery: "배송",
      revisions: "수정",
      hireSeller: "판매자 고용",
      contactSeller: "판매자에게 연락",
      memberSince: "가입일",
      aboutSeller: "판매자 정보",
      sellerGigs: "이 판매자의 활성 서비스",
      contact: "연락하기",
      reviewsTitle: "리뷰 및 평점",
      leaveReview: "리뷰 남기기",
      writeReview: "경험에 대해 작성해주세요...",
      submitReview: "리뷰 등록",
      days: "일",
      verifiedSeller: "인증된 판매자",
      reviewsCountLabel: "개의 리뷰",
      securePayment: "안전한 Pi 결제",
      satisfaction: "만족도 보장",
      support: "연중무휴 지원",
      guestUser: "게스트 사용자",
      msgPlaceholder: "메시지를 입력하세요...",
      msgOnline: "온라인",
      msgYourMessages: "내 메시지",
      msgTopic: "주제:",
      msgSystemWelcome: "SkillClick 채팅에 오신 것을 환영합니다! 👋",
      msgStartConv: "관련 대화 시작:",
      notificationsTitle: "알림",
      new: "새로운",
      noNotifications: "새 알림이 없습니다",
      earnings: "수익",
      member: "SkillClick 회원",
      tabOrders: "내 구매",
      tabSales: "내 판매",
      tabWallet: "지갑 및 정보",
      tabFavorites: "즐겨찾기",
      noPurchases: "구매 내역이 없습니다.",
      noSales: "판매 내역이 없습니다.",
      noFavorites: "즐겨찾기한 광고가 없습니다.",
      seller: "판매자",
      buyer: "구매자",
      date: "날짜",
      statusPaid: "지급 완료",
      statusPending: "대기 중",
      statusWaiting: "구매자 대기",
      walletTitle: "Pi 지급 지갑",
      walletDesc: "공개 키('G'로 시작)를 입력하세요. 수익이 이곳으로 자동 전송됩니다.",
      labelWallet: "Pi 지갑 주소 (G...)",
      btnSave: "주소 저장",
      savedMsg: "✅ 주소가 저장되었습니다! 수익이 자동으로 도착합니다.",
      notLogged: "로그인되지 않음",
      loginReq: "프로필을 보려면 Pi 브라우저를 통해 로그인해야 합니다.",
      error: "프로필 데이터를 불러오는 중 오류가 발생했습니다.",
      rated: "평가됨",
      // --- NOVO DODATO ---
      btnDispute: "분쟁 시작",
      btnCancelDispute: "분쟁 취소",
      statusDisputed: "분쟁 중",
      statusRefunded: "환불됨",
      confirmDispute: "분쟁을 시작하시겠습니까? 자금이 동결됩니다.",
      disputeOpened: "분쟁이 성공적으로 시작되었습니다.",
      confirmCancelDispute: "분쟁을 취소하시겠습니까? 주문이 대기 상태로 돌아갑니다.",
      disputeCanceled: "분쟁이 취소되었습니다.",
      pendingAdWarning: "미리보기: 이 광고는 승인 대기 중입니다!",
      buyBtn: "지금 구매",
      loginToBuy: "구매하려면 로그인",
      processing: "처리 중...",
      buySelfError: "자신의 서비스는 구매할 수 없습니다.",
      confirmBuyMsg: "이 서비스를 구매하시겠습니까? 가격:",
      buySuccess: "성공적으로 구매했습니다!",
      incompletePaymentFixed: "✅ 막힌 거래가 해결되었습니다! 다시 구매를 클릭하세요."
    },

    // === 🇩🇪 NEMAČKI ===
    de: {
      back: "Zurück",
      backHome: "Zurück zur Startseite",
      piLoginBtn: "Mit Pi anmelden",
      piLoginDesc: "Greifen Sie sicher über das Pi Network auf Ihr Konto zu.",
      piLoginDisclaimer: "Durch Klicken erlauben Sie SkillClick, Ihr Pi-Konto zu verifizieren.",
      piConnecting: "Verbindung zum Pi Network wird hergestellt...",
      piVerifying: "Wird verifiziert...",
      piBrowserError: "Bitte öffnen Sie diese App im Pi Browser.",
      piAuthFailed: "Authentifizierung fehlgeschlagen. Versuchen Sie es erneut.",
      piWelcomeUser: "Willkommen",
      welcomeBack: "Willkommen zurück",
      securedBy: "Gesichert durch Invictus System",
      loading: "Wird geladen...",
      navLogin: "Anmelden",
      navJoin: "Beitreten",
      navPostService: "Service anbieten",
      navProfile: "Mein Profil",
      navAdminPanel: "Admin-Panel",
      navLogout: "Abmelden",
      heroTitle: "Fähigkeiten finden, mit Pi bezahlen",
      heroSubtitle: "Globaler Marktplatz für die Pi Network Community.",
      catDesign: "Grafik & Design",
      catMarketing: "Digitales Marketing",
      catWriting: "Schreiben & Übersetzen",
      catVideo: "Video & Animation",
      catTech: "Programmierung & Technik",
      catBusiness: "Business",
      catLifestyle: "Lifestyle",
      searchPlaceholder: "Welchen Service suchen Sie?",
      searchBtn: "Suchen",
      popularTag: "Beliebt:",
      adsTitle: "Beliebte Dienstleistungen",
      exploreBest: "Entdecken Sie die besten Angebote",
      viewAll: "Alle ansehen",
      noReviews: "Noch keine Bewertungen.",
      createTitle: "Neuen Service anbieten",
      createSubtitle: "Zeigen Sie der Welt Ihr Talent",
      labelTitle: "Servicetitel",
      placeholderTitle: "z.B. Ich entwerfe ein modernes Logo für Sie",
      labelCategory: "Kategorie",
      selectCategory: "Kategorie auswählen",
      labelPrice: "Preis (Pi)",
      labelDelivery: "Lieferzeit (Tage)",
      labelDesc: "Beschreibung",
      placeholderDesc: "Beschreiben Sie Ihren Service im Detail...",
      uploadImages: "Bilder hochladen",
      uploadHint: "Max. 2MB pro Bild",
      coverImage: "Titelbild",
      imageLabel: "Bild",
      btnPublish: "Service veröffentlichen",
      successMessage: "Service erfolgreich veröffentlicht!",
      masterAdmin: "Master-Admin",
      totalEarnings: "Gesamteinnahmen",
      activeGigs: "Aktive Angebote",
      totalUsers: "Gesamte Benutzer",
      manageUsers: "Benutzer verwalten",
      manageServices: "Dienste verwalten",
      servicePrice: "Servicepreis",
      aboutService: "Über diesen Service",
      delivery: "Lieferung",
      revisions: "Überarbeitungen",
      hireSeller: "Verkäufer beauftragen",
      contactSeller: "Verkäufer kontaktieren",
      memberSince: "Mitglied seit",
      aboutSeller: "Über den Verkäufer",
      sellerGigs: "Aktive Angebote des Verkäufers",
      contact: "Kontakt",
      reviewsTitle: "Bewertungen & Ratings",
      leaveReview: "Bewertung hinterlassen",
      writeReview: "Schreiben Sie über Ihre Erfahrungen...",
      submitReview: "Bewertung absenden",
      days: "Tage",
      verifiedSeller: "Verifizierter Verkäufer",
      reviewsCountLabel: "Bewertungen",
      securePayment: "Sichere Pi-Zahlung",
      satisfaction: "Zufriedenheitsgarantie",
      support: "24/7 Support",
      guestUser: "Gast",
      msgPlaceholder: "Nachricht tippen...",
      msgOnline: "Online",
      msgYourMessages: "Ihre Nachrichten",
      msgTopic: "Thema:",
      msgSystemWelcome: "Willkommen im SkillClick-Chat! 👋",
      msgStartConv: "Gespräch beginnen bezüglich:",
      notificationsTitle: "Benachrichtigungen",
      new: "neu",
      noNotifications: "Keine neuen Benachrichtigungen",
      earnings: "Einnahmen",
      member: "Mitglied bei SkillClick",
      tabOrders: "Meine Käufe",
      tabSales: "Meine Verkäufe",
      tabWallet: "Wallet & Info",
      tabFavorites: "Favoriten",
      noPurchases: "Noch keine Käufe.",
      noSales: "Noch keine Verkäufe.",
      noFavorites: "Noch keine Lieblingsanzeigen.",
      seller: "Verkäufer",
      buyer: "Käufer",
      date: "Datum",
      statusPaid: "BEZAHLT",
      statusPending: "AUSSTEHEND",
      statusWaiting: "Wartet auf Käufer",
      walletTitle: "Ihre Pi Auszahlungs-Wallet",
      walletDesc: "Geben Sie Ihren Public Key ein (beginnt mit 'G'). Einnahmen werden automatisch hierhin gesendet.",
      labelWallet: "Pi Wallet Adresse (G...)",
      btnSave: "Adresse speichern",
      savedMsg: "✅ Adresse gespeichert! Einnahmen kommen automatisch an.",
      notLogged: "Nicht angemeldet",
      loginReq: "Sie müssen sich über den Pi Browser anmelden, um Ihr Profil anzuzeigen.",
      error: "Fehler beim Laden der Profildaten.",
      rated: "Bewertet",
      // --- NOVO DODATO ---
      btnDispute: "Streitfall eröffnen",
      btnCancelDispute: "Streitfall abbrechen",
      statusDisputed: "IM STREITFALL",
      statusRefunded: "ERSTATTET",
      confirmDispute: "Möchten Sie wirklich einen Streitfall eröffnen? Gelder werden eingefroren.",
      disputeOpened: "Streitfall erfolgreich eröffnet.",
      confirmCancelDispute: "Möchten Sie den Streitfall wirklich abbrechen?",
      disputeCanceled: "Streitfall erfolgreich abgebrochen.",
      pendingAdWarning: "VORSCHAU: Diese Anzeige wartet auf Genehmigung!",
      buyBtn: "Jetzt kaufen",
      loginToBuy: "Zum Kauf anmelden",
      processing: "Verarbeitung...",
      buySelfError: "Sie können Ihren eigenen Service nicht kaufen.",
      confirmBuyMsg: "Möchten Sie diesen Service wirklich kaufen für",
      buySuccess: "Erfolgreich gekauft!",
      incompletePaymentFixed: "✅ Feststeckende Transaktion gelöscht! Bitte erneut auf Kaufen klicken."
    },

    // === 🇷🇺 RUSKI ===
    ru: {
      back: "Назад",
      backHome: "На главную",
      piLoginBtn: "Войти через Pi",
      piLoginDesc: "Безопасный доступ к аккаунту через Pi Network.",
      piLoginDisclaimer: "Нажимая, вы разрешаете SkillClick проверить ваш аккаунт Pi.",
      piConnecting: "Подключение к Pi Network...",
      piVerifying: "Проверка...",
      piBrowserError: "Пожалуйста, откройте это приложение в Pi Browser.",
      piAuthFailed: "Ошибка аутентификации. Попробуйте еще раз.",
      piWelcomeUser: "Добро пожаловать",
      welcomeBack: "С возвращением",
      securedBy: "Защищено системой Invictus",
      loading: "Загрузка...",
      navLogin: "Войти",
      navJoin: "Регистрация",
      navPostService: "Создать услугу",
      navProfile: "Мой профиль",
      navAdminPanel: "Панель администратора",
      navLogout: "Выйти",
      heroTitle: "Найди навык, плати в Pi",
      heroSubtitle: "Глобальная платформа для сообщества Pi Network.",
      catDesign: "Графика и дизайн",
      catMarketing: "Цифровой маркетинг",
      catWriting: "Тексты и переводы",
      catVideo: "Видео и анимация",
      catTech: "Программирование и ИТ",
      catBusiness: "Бизнес",
      catLifestyle: "Стиль жизни",
      searchPlaceholder: "Какую услугу вы ищете?",
      searchBtn: "Поиск",
      popularTag: "Популярное:",
      adsTitle: "Популярные услуги",
      exploreBest: "Изучите лучшие предложения",
      viewAll: "Смотреть все",
      noReviews: "Пока нет отзывов.",
      createTitle: "Опубликовать новую услугу",
      createSubtitle: "Покажите свой талант миру",
      labelTitle: "Название услуги",
      placeholderTitle: "напр. Я разработаю для вас современный логотип",
      labelCategory: "Категория",
      selectCategory: "Выберите категорию",
      labelPrice: "Цена (Pi)",
      labelDelivery: "Срок выполнения (дней)",
      labelDesc: "Описание",
      placeholderDesc: "Подробно опишите вашу услугу...",
      uploadImages: "Загрузить изображения",
      uploadHint: "Макс. 2 МБ на изображение",
      coverImage: "Обложка",
      imageLabel: "Изображение",
      btnPublish: "Опубликовать услугу",
      successMessage: "Услуга успешно опубликована!",
      masterAdmin: "Главный администратор",
      totalEarnings: "Общий заработок",
      activeGigs: "Активные услуги",
      totalUsers: "Всего пользователей",
      manageUsers: "Управление пользователями",
      manageServices: "Управление услугами",
      servicePrice: "Цена услуги",
      aboutService: "Об этой услуге",
      delivery: "Доставка",
      revisions: "Правки",
      hireSeller: "Нанять продавца",
      contactSeller: "Связаться с продавцом",
      memberSince: "На сайте с",
      aboutSeller: "О продавце",
      sellerGigs: "Активные услуги продавца",
      contact: "Контакты",
      reviewsTitle: "Отзывы и оценки",
      leaveReview: "Оставить отзыв",
      writeReview: "Напишите о своем опыте...",
      submitReview: "Отправить отзыв",
      days: "дней",
      verifiedSeller: "Проверенный продавец",
      reviewsCountLabel: "отзывов",
      securePayment: "Безопасная оплата Pi",
      satisfaction: "Гарантия качества",
      support: "Круглосуточная поддержка",
      guestUser: "Гость",
      msgPlaceholder: "Введите сообщение...",
      msgOnline: "В сети",
      msgYourMessages: "Ваши сообщения",
      msgTopic: "Тема:",
      msgSystemWelcome: "Добро пожаловать в чат SkillClick! 👋",
      msgStartConv: "Начало диалога по теме:",
      notificationsTitle: "Уведомления",
      new: "новых",
      noNotifications: "Нет новых уведомлений",
      earnings: "Заработок",
      member: "Участник SkillClick",
      tabOrders: "Мои покупки",
      tabSales: "Мои продажи",
      tabWallet: "Кошелек и информация",
      tabFavorites: "Избранное",
      noPurchases: "Пока нет покупок.",
      noSales: "Пока нет продаж.",
      noFavorites: "Нет любимых объявлений.",
      seller: "Продавец",
      buyer: "Покупатель",
      date: "Дата",
      statusPaid: "ОПЛАЧЕНО",
      statusPending: "В ОЖИДАНИИ",
      statusWaiting: "Ожидание покупателя",
      walletTitle: "Ваш кошелек Pi для выплат",
      walletDesc: "Введите ваш публичный ключ (начинается с 'G'). Заработок будет автоматически отправляться сюда.",
      labelWallet: "Адрес кошелька Pi (G...)",
      btnSave: "Сохранить адрес",
      savedMsg: "✅ Адрес сохранен! Заработок будет поступать автоматически.",
      notLogged: "Вы не вошли в систему",
      loginReq: "Вам необходимо войти через Pi Browser для просмотра профиля.",
      error: "Ошибка загрузки данных профиля.",
      rated: "Оценено",
      // --- NOVO DODATO ---
      btnDispute: "Открыть спор",
      btnCancelDispute: "Отменить спор",
      statusDisputed: "СПОР",
      statusRefunded: "ВОЗВРАТ",
      confirmDispute: "Вы уверены, что хотите открыть спор? Средства будут заморожены.",
      disputeOpened: "Спор успешно открыт.",
      confirmCancelDispute: "Вы уверены, что хотите отменить спор?",
      disputeCanceled: "Спор успешно отменен.",
      pendingAdWarning: "ПРЕДПРОСМОТР: Это объявление ожидает одобрения!",
      buyBtn: "Купить сейчас",
      loginToBuy: "Войдите, чтобы купить",
      processing: "Обработка...",
      buySelfError: "Вы не можете купить собственную услугу.",
      confirmBuyMsg: "Вы уверены, что хотите купить эту услугу за",
      buySuccess: "Успешная покупка!",
      incompletePaymentFixed: "✅ Зависшая транзакция очищена! Пожалуйста, нажмите купить еще раз."
    },

    // === 🇫🇷 FRANCUSKI ===
    fr: {
      back: "Retour",
      backHome: "Retour à l'accueil",
      piLoginBtn: "Se connecter avec Pi",
      piLoginDesc: "Accédez à votre compte en toute sécurité avec Pi Network.",
      piLoginDisclaimer: "En cliquant, vous autorisez SkillClick à vérifier votre compte Pi.",
      piConnecting: "Connexion au Pi Network...",
      piVerifying: "Vérification...",
      piBrowserError: "Veuillez ouvrir cette application dans le Pi Browser.",
      piAuthFailed: "L'authentification a échoué. Réessayez.",
      piWelcomeUser: "Bienvenue",
      welcomeBack: "Bon retour",
      securedBy: "Sécurisé par le système Invictus",
      loading: "Chargement...",
      navLogin: "Connexion",
      navJoin: "S'inscrire",
      navPostService: "Publier un service",
      navProfile: "Mon Profil",
      navAdminPanel: "Panneau d'administration",
      navLogout: "Déconnexion",
      heroTitle: "Trouvez des compétences, payez en Pi",
      heroSubtitle: "La place de marché mondiale pour la communauté Pi Network.",
      catDesign: "Graphisme & Design",
      catMarketing: "Marketing Digital",
      catWriting: "Rédaction & Traduction",
      catVideo: "Vidéo & Animation",
      catTech: "Programmation & Tech",
      catBusiness: "Business",
      catLifestyle: "Style de vie",
      searchPlaceholder: "Quel service recherchez-vous ?",
      searchBtn: "Rechercher",
      popularTag: "Populaire :",
      adsTitle: "Services Populaires",
      exploreBest: "Explorez les meilleures offres",
      viewAll: "Voir tout",
      noReviews: "Aucun avis pour le moment.",
      createTitle: "Publier un nouveau service",
      createSubtitle: "Montrez votre talent au monde entier",
      labelTitle: "Titre du service",
      placeholderTitle: "ex. Je vais concevoir un logo moderne pour vous",
      labelCategory: "Catégorie",
      selectCategory: "Sélectionnez une catégorie",
      labelPrice: "Prix (Pi)",
      labelDelivery: "Délai de livraison (jours)",
      labelDesc: "Description",
      placeholderDesc: "Décrivez votre service en détail...",
      uploadImages: "Télécharger des images",
      uploadHint: "Max 2 Mo par image",
      coverImage: "Image de couverture",
      imageLabel: "Image",
      btnPublish: "Publier le service",
      successMessage: "Service publié avec succès !",
      masterAdmin: "Administrateur principal",
      totalEarnings: "Gains totaux",
      activeGigs: "Services actifs",
      totalUsers: "Utilisateurs totaux",
      manageUsers: "Gérer les utilisateurs",
      manageServices: "Gérer les services",
      servicePrice: "Prix du service",
      aboutService: "À propos de ce service",
      delivery: "Livraison",
      revisions: "Révisions",
      hireSeller: "Embaucher",
      contactSeller: "Contacter le vendeur",
      memberSince: "Membre depuis",
      aboutSeller: "À propos du vendeur",
      sellerGigs: "Services actifs du vendeur",
      contact: "Contact",
      reviewsTitle: "Avis & Évaluations",
      leaveReview: "Laisser un avis",
      writeReview: "Décrivez votre expérience...",
      submitReview: "Publier l'avis",
      days: "jours",
      verifiedSeller: "Vendeur vérifié",
      reviewsCountLabel: "avis",
      securePayment: "Paiement Pi Sécurisé",
      satisfaction: "Satisfaction garantie",
      support: "Support 24/7",
      guestUser: "Invité",
      msgPlaceholder: "Tapez un message...",
      msgOnline: "En ligne",
      msgYourMessages: "Vos messages",
      msgTopic: "Sujet :",
      msgSystemWelcome: "Bienvenue sur le chat SkillClick ! 👋",
      msgStartConv: "Début de la conversation concernant :",
      notificationsTitle: "Notifications",
      new: "nouveau",
      noNotifications: "Aucune nouvelle notification",
      earnings: "Gains",
      member: "Membre de SkillClick",
      tabOrders: "Mes Achats",
      tabSales: "Mes Ventes",
      tabWallet: "Portefeuille & Info",
      tabFavorites: "Favoris",
      noPurchases: "Aucun achat pour le moment.",
      noSales: "Aucune vente pour le moment.",
      noFavorites: "Aucune annonce favorite.",
      seller: "Vendeur",
      buyer: "Acheteur",
      date: "Date",
      statusPaid: "PAYÉ",
      statusPending: "EN ATTENTE",
      statusWaiting: "En attente de l'acheteur",
      walletTitle: "Votre portefeuille de paiement Pi",
      walletDesc: "Entrez votre clé publique (commence par 'G'). Les gains seront envoyés ici automatiquement.",
      labelWallet: "Adresse du portefeuille Pi (G...)",
      btnSave: "Enregistrer l'adresse",
      savedMsg: "✅ Adresse enregistrée ! Les gains arriveront automatiquement.",
      notLogged: "Non connecté",
      loginReq: "Vous devez vous connecter via le navigateur Pi pour voir votre profil.",
      error: "Erreur de chargement des données du profil.",
      rated: "Évalué",
      // --- NOVO DODATO ---
      btnDispute: "Ouvrir un litige",
      btnCancelDispute: "Annuler le litige",
      statusDisputed: "EN LITIGE",
      statusRefunded: "REMBOURSÉ",
      confirmDispute: "Voulez-vous vraiment ouvrir un litige ? Les fonds seront gelés.",
      disputeOpened: "Litige ouvert avec succès.",
      confirmCancelDispute: "Voulez-vous vraiment annuler le litige ?",
      disputeCanceled: "Litige annulé avec succès.",
      pendingAdWarning: "APERÇU : Cette annonce est en attente d'approbation !",
      buyBtn: "Acheter maintenant",
      loginToBuy: "Connectez-vous pour acheter",
      processing: "Traitement...",
      buySelfError: "Vous ne pouvez pas acheter votre propre service.",
      confirmBuyMsg: "Voulez-vous vraiment acheter ce service pour",
      buySuccess: "Achat réussi !",
      incompletePaymentFixed: "✅ Transaction bloquée effacée ! Veuillez cliquer à nouveau sur acheter."
    }
  };

  const t = (key: string) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    return { language: 'en', setLanguage: () => {}, t: (key: string) => key };
  }
  return context;
};
